#include <iostream>
#include <string_view>
#include <cmath>
#include <string>

#include <glad/glad.h>

#include <imgui/imgui.h>
#include <imgui/backends/imgui_impl_sdl3.h>
#include <imgui/backends/imgui_impl_opengl3.h>
#include <SDL3/SDL.h>

#include <spdlog/spdlog.h>
#include <spdlog/fmt/bundled/color.h>

#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>

#include <CLI/CLI.hpp>

#include "GraphicsWindow.h"
#include "graphics/OGLShader.h"
#include "graphics/ShaderProgram.h"
#include "graphics/FImage.h"

#include "graphics/PrebuiltShaderSources.h"

#include "video/camera/common/CameraBase.h"
#include "video/camera/common/CameraHelpers.h"
#include "video/camera/Camera.h"

#include "gui/CameraMenu.h"

#include "support/logging.h"
#include "support/utility.h"

void SetupShaderParams(const ShaderProgram & shader_program);
bool WindowResize(void * data, SDL_Event * event);
void PrintStartMessage();
float RenderElapsedTime();

constexpr int32_t window_width  = 640;
constexpr int32_t window_height = 480;

int32_t main(int32_t argc, char*argv[])
{
  logging::set_logging_output();
  utility::EnableConsoleMode();

  CLI::App app("easily setup graphics source for getting started with opengl and potentially other graphic libraries for <reason for template>", "graphics");

  // add command line options,flags,etc

  uint32_t device_index = 0;
  app.add_option("--device-idx", device_index, "camera enumerated index");

  std::string choose_camera_format = "0";
  app.add_option("-f,--format", choose_camera_format, "camera formats: uyvy[0], yuy2[1], nv12[2], rgb[3], rgba[4] ,mjpg[5]");

  bool ignore_camera_failed_format = false;
  app.add_flag("--ignore-format-fail", ignore_camera_failed_format, "if true it will copy what it can from from the frame generated by the camera instead of ignoring the frame");


  CLI11_PARSE(app, argc, argv)

  gss::video::camera::types::VideoFormat camera_format = gss::video::camera::helpers::get_format_by_index(choose_camera_format);

  PrintStartMessage();

  // sdl and window initialization

  constexpr static std::string_view window_name = "Graphics Window";
  constexpr uint64_t sdl_window_flags = SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE;

  auto graphics_window = GraphicsWindow(window_name.data(), window_width, window_height, sdl_window_flags);
  SDL_GL_MakeCurrent(graphics_window.GetSDLWindow(), graphics_window.GetOpenGLContext()->GetContext());

  if (!graphics_window.IsWindowInitialized())
  {
    logging::error("Unable to initialize a window!!!");
    return 0;
  }

  gladLoadGLLoader(reinterpret_cast<GLADloadproc>(SDL_GL_GetProcAddress));

  const OGLShader vshader(prebuilt_shaders::vertex_shader_code.data(), OGLShader::ShaderType::VERTEX);
  const OGLShader fshader(prebuilt_shaders::fragment_shader_code.data(), OGLShader::ShaderType::FRAGMENT);
  const ShaderProgram shader_program(vshader, fshader);
  shader_program.Use();

  // Init Sprite with Texture
  FImage sprite;
  sprite.LoadTexture(std::string(PROJECT_ROOT_PATH) + "images/park.jpg");
  shader_program.SetTexture2D("image", sprite.GetTexture());

  // do some setup work here
  constexpr gss::video::camera::types::FrameRate camera_fps = {30, 1};
  const std::shared_ptr<gss::video::camera::CameraBase> camera = std::make_shared<gss::video::camera::Camera>(device_index, window_width, window_height, camera_fps, camera_format, ignore_camera_failed_format);
  camera->StartCapture();

  gss::video::camera::types::FrameSize current_frame_size = camera->GetResolution();

  // initialize imGUI
  ImGui::CreateContext();
  ImGui::StyleColorsDark();

  CameraMenu camera_menu(camera.get());

  constexpr std::string_view glsl_version = "#version 450";
  ImGui_ImplSDL3_InitForOpenGL(graphics_window.GetSDLWindow(), graphics_window.GetOpenGLContext()->GetContext());
  ImGui_ImplOpenGL3_Init(glsl_version.data());

  SetupShaderParams(shader_program);

  SDL_AddEventWatch(WindowResize, graphics_window.GetSDLWindow());

  bool is_running = true;

  // event handling

  SDL_Event sdl_event;

  while (is_running)
  {
    while (SDL_PollEvent(&sdl_event))
    {
      ImGui_ImplSDL3_ProcessEvent(&sdl_event);

      if (sdl_event.type == SDL_EVENT_QUIT)
      {
        is_running = false;
      }
    }

    ImGui_ImplOpenGL3_NewFrame();
    ImGui_ImplSDL3_NewFrame();
    ImGui::NewFrame();

    // do imgui work

    camera_menu.RenderMenu();

    ImGui::Render();
    GraphicsWindow::ClearWindow();

    // do work

    auto model_matrix = glm::mat4(1.0f);
    model_matrix = glm::translate(model_matrix, sprite.GetPosition());
    model_matrix = glm::scale(model_matrix, {current_frame_size.first, current_frame_size.second, 1.0f});
    shader_program.SetFloat4x4("model", glm::value_ptr(model_matrix));

    if (current_frame_size.first != camera->GetResolution().first || current_frame_size.second != camera->GetResolution().second)
    {
      current_frame_size = camera->GetResolution();
      SDL_SetWindowSize(graphics_window.GetSDLWindow(), current_frame_size.first, current_frame_size.second);
    }

    if (const std::shared_ptr<FImage> frame = camera->ExtractFrame())
    {
      frame->UpdateImageFilter(frame->GetFinalImageFilterID());
      frame->ViewTexture();
    }

    sprite.Draw();

    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
    graphics_window.SwapBuffers();
  }

  // cleanup

  camera->StopCapture();

  ImGui_ImplOpenGL3_Shutdown();
  ImGui_ImplSDL3_Shutdown();
  ImGui::DestroyContext();

  graphics_window.Destroy();
  SDL_Quit();

  return 0;
}

void SetupShaderParams(const ShaderProgram & shader_program)
{
  constexpr float l = -window_width / 2.0f;
  constexpr float r =  window_width / 2.0f;
  constexpr float b =  window_height / 2.0f;
  constexpr float t = -window_height / 2.0f;
  constexpr float n = -1.0f;
  constexpr float f =  1.0f;

  auto ortho_matrix = glm::ortho(l, r, b, t, n, f);
  shader_program.SetFloat4x4("ortho", glm::value_ptr(ortho_matrix));

  static float timeValue = 0.01f;
  timeValue += 0.05f;

  const float green_value = std::sin(timeValue) / 2.0f + 0.5f;
  const float red_value = std::cos(timeValue) / 2.0f + 0.5f;
  const float blue_value = std::sin(timeValue) / 3.0f + 0.5f;
  const float color[] = {red_value, green_value, blue_value};

  shader_program.SetFloat4("color", color);
}

bool WindowResize(void * data, SDL_Event * event)
{
  bool event_handled = false;

  if (event->window.type == SDL_EVENT_WINDOW_RESIZED)
  {
    const SDL_Window* window = SDL_GetWindowFromID(event->window.windowID);
    if (window == static_cast<SDL_Window*>(data))
    {
      logging::info(fmt::format(fmt::fg(fmt::terminal_color::bright_white) | fmt::emphasis::bold, "window resizing..."));
      glViewport(0, 0, event->window.data1, event->window.data2);
      event_handled = true;
    }
  }

  return event_handled;
}

void PrintStartMessage()
{
  logging::info(fmt::format(fmt::fg(fmt::terminal_color::bright_white) | fmt::emphasis::bold,"Starting: Hello, Graphics World!"));
}
