#include <iostream>
#include <string_view>
#include <cmath>
#include <string>
#include <numbers>

#include <glad/glad.h>

#include <imgui/imgui.h>
#include <imgui/backends/imgui_impl_sdl3.h>
#include <imgui/backends/imgui_impl_opengl3.h>
#include <SDL3/SDL.h>

#include "common/support/logging.h"
#include <spdlog/fmt/bundled/color.h>

#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>

#include <CLI/CLI.hpp>

#include "GraphicsWindow.h"
#include "graphics/shaders/OGLShader.h"
#include "graphics/shaders/ShaderProgram.h"
#include "graphics/images/FImage.h"

#include "graphics/shaders/PrebuiltShaderSources.h"

#include "support/logging.h"
#include "support/utility.h"

#include "video/camera/Camera.h"
#include "video/camera/common/CameraHelpers.h"
#include "video/camera/common/CameraFormats.h"
#include "video/RosVideoFeed.h"
#include "process/PixelFormatConversionBlock.h"

#include "gui/CameraMenu.h"
#include "gui/PixelCornersMenu.h"
#include "gui/ImageBlockViewMenu.h"
#include "gui/SceneDepthMenu.h"

#include "process/PixelEdgeBlock.h"
#include "process/PixelCornersBlock.h"
#include "process/NonMaximumSuppressBlock.h"
#include "process/OpticalFlowBlock.h"
#include "process/SceneDepthBlock.h"

void SetupShaderParams(const ShaderProgram & shader_program);
bool WindowResize(void * data, SDL_Event * event);
void PrintStartMessage();
float RenderElapsedTime();

constexpr int32_t window_width  = 640;
constexpr int32_t window_height = 480;

int32_t main(int32_t argc, char*argv[])
{
  logging::set_logging_output();
  utility::EnableConsoleMode();

  CLI::App app("easily setup graphics source for getting started with opengl and potentially other graphic libraries for <reason for template>", "graphics");

  // add command line options,flags,etc

  uint32_t device_index = 0;
  app.add_option("--device-idx", device_index, "camera enumerated index");

  std::string choose_camera_format = "0";
  app.add_option("-f,--format", choose_camera_format, "camera formats: uyvy[0], yuy2[1], nv12[2], rgb[3], rgba[4] ,mjpg[5]");

  bool ignore_camera_failed_format = false;
  app.add_flag("--ignore-format-fail", ignore_camera_failed_format, "if true it will copy what it can from from the frame generated by the camera instead of ignoring the frame");

  int single_cam = -1;
  app.add_option("--single-cam", single_cam, "default looks for 2 cameras, [0] look for first camera only, [1] look for second camera only");

  float cam_rotation = 0.0f;
  app.add_option("--cam-rot", cam_rotation, "Set camera initial rotation in degrees");

  CLI11_PARSE(app, argc, argv)

  gss::video::camera::types::VideoFormat camera_format = gss::video::camera::helpers::get_format_by_index(choose_camera_format);
  gss::video::camera::types::VideoFormat camera_format_2 = gss::video::camera::helpers::get_format_by_index("0");
  //gss::video::camera::types::VideoFormat camera_format_2 = gss::video::camera::helpers::get_format_by_index("1");

  PrintStartMessage();

  // sdl and window initialization

  constexpr static std::string_view window_name = "Graphics Window";
  constexpr uint64_t sdl_window_flags = SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE;

  auto graphics_window = GraphicsWindow(window_name.data(), window_width, window_height, sdl_window_flags);
  SDL_GL_MakeCurrent(graphics_window.GetSDLWindow(), graphics_window.GetOpenGLContext()->GetContext());

  if (!graphics_window.IsWindowInitialized())
  {
    logging::error("Unable to initialize a window!!!");
    return 0;
  }

  gladLoadGLLoader(reinterpret_cast<GLADloadproc>(SDL_GL_GetProcAddress));

  const OGLShader vshader(prebuilt_shaders::vertex_shader_code.data(), OGLShader::ShaderType::VERTEX);
  const OGLShader fshader(prebuilt_shaders::fragment_shader_code.data(), OGLShader::ShaderType::FRAGMENT);
  const ShaderProgram shader_program(vshader, fshader);
  shader_program.Use();

  // Init Sprite with Texture
  FImage sprite;
  sprite.LoadTexture(std::string(PROJECT_ROOT_PATH) + "images/park.jpg");
  shader_program.SetTexture2D("image", sprite.GetTexture());

  // do some setup work here
  constexpr gss::video::camera::types::FrameRate camera_fps = {1, 30};
  //[[maybe_unused]] gss::video::camera::Camera ref_camera_hold(device_index, window_width, window_height, camera_fps, camera_format, ignore_camera_failed_format);
  gss::video::camera::Camera ref_camera(device_index, window_width, window_height, camera_fps, camera_format, ignore_camera_failed_format);
  //RosVideoFeed ref_camera;
  gss::video::camera::Camera sec_camera(device_index + 1, window_width, window_height, camera_fps, camera_format_2, ignore_camera_failed_format);

  if (single_cam < 0)
  {
    ref_camera.StartCapture();
    sec_camera.StartCapture();
  }
  else if (single_cam == 0)
  {
    ref_camera.StartCapture();
  }
  else // if (single_cam == 1)
  {
    sec_camera.StartCapture();
  }

  gss::video::camera::types::FrameSize current_frame_size = ref_camera.GetResolution();

  auto process_scene_depth_block = std::make_shared<SceneDepthBlock>("scenedepthblock", "scene depth from multiple cameras");
  auto process_optical_flow_block = std::make_shared<OpticalFlowBlock>("optflowblock", "optical flow from points");
  auto process_non_max_sup_block = std::make_shared<NonMaximumSuppressBlock>("nmsblock", "curtails corners", ImageBlockList{process_optical_flow_block});
  auto process_corners_block = std::make_shared<PixelCornersBlock>("cornersblock", "process corners from image", ImageBlockList{process_non_max_sup_block});
  auto process_edge_block = std::make_shared<PixelEdgeBlock>("edgeblock", "process edges from image");
  auto process_format_block = std::make_shared<PixelFormatConversionBlock>("fmtblock", "convert uyvy to rgb", ImageBlockList{process_edge_block, process_corners_block});

  process_format_block->Enable(true);
  process_edge_block->Enable(true);
  process_corners_block->Enable(true);
  process_non_max_sup_block->Enable(true);
  process_optical_flow_block->Enable(true);
  process_scene_depth_block->Enable(true);

  CameraMenu camera_menu_sec(&sec_camera, nullptr);
  CameraMenu camera_menu(&ref_camera, process_format_block.get());
  PixelCornersMenu pixel_corners_menu(process_corners_block.get(), process_non_max_sup_block.get(), process_optical_flow_block.get());
  ImageBlockViewMenu image_block_menu({process_format_block.get(), process_edge_block.get(), process_corners_block.get(), process_non_max_sup_block.get(), process_optical_flow_block.get(), process_scene_depth_block.get()});
  SceneDepthMenu scene_depth_menu(process_scene_depth_block.get());

  // initialize imGUI
  ImGui::CreateContext();
  ImGui::StyleColorsDark();

  constexpr std::string_view glsl_version = "#version 450";
  ImGui_ImplSDL3_InitForOpenGL(graphics_window.GetSDLWindow(), graphics_window.GetOpenGLContext()->GetContext());
  ImGui_ImplOpenGL3_Init(glsl_version.data());

  SDL_AddEventWatch(WindowResize, graphics_window.GetSDLWindow());

  bool is_running = true;

  // event handling

  SDL_Event sdl_event;

  while (is_running)
  {
    while (SDL_PollEvent(&sdl_event))
    {
      ImGui_ImplSDL3_ProcessEvent(&sdl_event);

      if (sdl_event.type == SDL_EVENT_QUIT)
      {
        is_running = false;
      }
    }

    ImGui_ImplOpenGL3_NewFrame();
    ImGui_ImplSDL3_NewFrame();
    ImGui::NewFrame();

    // do imgui work

    camera_menu.RenderMenu();
    camera_menu_sec.RenderMenu();
    pixel_corners_menu.RenderMenu();
    image_block_menu.RenderMenu();
    scene_depth_menu.RenderMenu();

    ImGui::Render();
    GraphicsWindow::ClearWindow();

    // do work

    SetupShaderParams(shader_program);

    if (current_frame_size.first != ref_camera.GetResolution().first || current_frame_size.second != ref_camera.GetResolution().second)
    {
      current_frame_size = ref_camera.GetResolution();
      SDL_SetWindowSize(graphics_window.GetSDLWindow(), static_cast<int32_t>(current_frame_size.first), static_cast<int32_t>(current_frame_size.second));
    }

    const auto frame_0 = ref_camera.CopyFrame();
    if (frame_0)
    {
      process_format_block->QueueToProcess({frame_0});
    }

    const auto frame_1 = sec_camera.CopyFrame();
    if (frame_0 && frame_1)
    {
      process_scene_depth_block->QueueToProcess({frame_0, frame_1});
    }

    if (auto process_frame = image_block_menu.GetImage())
    {
      process_frame->ViewTexture();
    }

    //sprite.SetPosition({100.0f * std::cos(location_time), 100.0f * std::sin(location_time)});
    //logging::info("time: {}", location_time);

    //static float r_value = 0.0f;
    //r_value +=  0.001f;

    auto model_matrix = glm::mat4(1.0f);
    model_matrix = glm::translate(model_matrix, sprite.GetPosition());
    //model_matrix = glm::rotate(model_matrix, glm::radians(location_time * -100.0f), {0.0f, 0.0f, 1.0f});
    model_matrix = glm::rotate(model_matrix, glm::radians(cam_rotation), {0.0f, 0.0f, 1.0f});
    model_matrix = glm::scale(model_matrix, {current_frame_size.first, current_frame_size.second, 1.0f});
    shader_program.SetFloat4x4("model", glm::value_ptr(model_matrix));

    sprite.Draw();

    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
    graphics_window.SwapBuffers();
  }

  // cleanup

  ImGui_ImplOpenGL3_Shutdown();
  ImGui_ImplSDL3_Shutdown();
  ImGui::DestroyContext();

  graphics_window.Destroy();
  SDL_Quit();

  return 0;
}

void SetupShaderParams(const ShaderProgram & shader_program)
{
  constexpr float l = -window_width / 2.0f;
  constexpr float r =  window_width / 2.0f;
  constexpr float b =  window_height / 2.0f;
  constexpr float t = -window_height / 2.0f;
  constexpr float n = -1.0f;
  constexpr float f =  1.0f;

  auto ortho_matrix = glm::ortho(l, r, b, t, n, f);
  shader_program.SetFloat4x4("ortho", glm::value_ptr(ortho_matrix));

  static float timeValue = 0.01f;
  timeValue += 0.05f;

  const float green_value = std::sin(timeValue) / 2.0f + 0.5f;
  const float red_value = std::cos(timeValue) / 2.0f + 0.5f;
  const float blue_value = std::sin(timeValue) / 3.0f + 0.5f;
  const float color[] = {red_value, green_value, blue_value};

  shader_program.SetFloat4("color", color);
}

bool WindowResize(void * data, SDL_Event * event)
{
  bool event_handled = false;

  if (event->window.type == SDL_EVENT_WINDOW_RESIZED)
  {
    const SDL_Window* window = SDL_GetWindowFromID(event->window.windowID);
    if (window == static_cast<SDL_Window*>(data))
    {
      logging::info(fmt::format(fmt::fg(fmt::terminal_color::bright_white) | fmt::emphasis::bold, "window resizing..."));
      glViewport(0, 0, event->window.data1, event->window.data2);
      event_handled = true;
    }
  }

  return event_handled;
}

void PrintStartMessage()
{
  logging::info(fmt::format(fmt::fg(fmt::terminal_color::bright_white) | fmt::emphasis::bold,"Starting: Hello, Graphics World!"));
}
